# Generated by Django 3.2.13 on 2023-05-21 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_liked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
